# Multiple Linear Regression

## Importing the libraries

Aim: Dep upon the #hours studied , #hours slept, IQ, loc   --->predict maks

In [1]:
import numpy as np
import pandas as pd

Creating the dataset

y = b0 +b1*x1 +b2*x2 +b3*x3 +b4*x4


In [2]:
from numpy.random import rand

df  = pd.DataFrame(rand( 50 , 3)*10, columns = 'Hours_studied Hours_slept iQ '.split())
df.head(2)

Hours_studied  Hours_slept        iQ
0       8.204758     8.851692  5.541916
1       7.384167     0.297860  0.913333

In [3]:
from random import choice

location = []
for i in range(50):
    
    location.append(choice(["New Delhi" , "Pune" , "Bangalore"]))
 

df['Location'] = location

df.head()

Hours_studied  Hours_slept        iQ   Location
0       8.204758     8.851692  5.541916       Pune
1       7.384167     0.297860  0.913333  New Delhi
2       6.709420     6.866250  0.560222       Pune
3       2.618587     2.435272  9.752401       Pune
4       9.492454     1.800359  4.000938  New Delhi

In [4]:
df['Marks'] = (1.73 + (3.34*df['Hours_studied'])
                    + (2.45*df['Hours_slept'])
                    + (1.83*df['iQ']  ))
df['Marks'] =  df['Marks'] +np.random.rand(50)*20
               
df.to_csv('Students.csv',index=False)


In [5]:
df.head()

Hours_studied  Hours_slept        iQ   Location      Marks
0       8.204758     8.851692  5.541916       Pune  61.353218
1       7.384167     0.297860  0.913333  New Delhi  33.931078
2       6.709420     6.866250  0.560222       Pune  45.547257
3       2.618587     2.435272  9.752401       Pune  38.786991
4       9.492454     1.800359  4.000938  New Delhi  64.524522

## Importing the dataset

In [6]:
dataset = pd.read_csv('Students.csv')

X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(X)

[[8.20475811907858 8.851691567052583 5.541915796453766 'Pune']
 [7.384167208052879 0.29786024544546263 0.9133332440410924 'New Delhi']
 [6.709420367634253 6.866250118762682 0.5602215602680827 'Pune']
 [2.6185867213836103 2.4352722247822367 9.752400544516247 'Pune']
 [9.492453803697988 1.8003594027005765 4.0009384506635115 'New Delhi']
 [0.37576603722391577 1.3842668716348183 6.396029703962327 'Pune']
 [5.489149445758447 6.44340864539905 4.03050107937026 'New Delhi']
 [7.999986512159232 0.5191311274589538 2.0954801469345465 'New Delhi']
 [8.921422662784611 3.4253335690767672 5.272097693438419 'Bangalore']
 [3.7617682880904377 4.549142039893949 9.718867035590838 'New Delhi']
 [2.908848728809585 9.590750163881113 9.531488100551908 'Bangalore']
 [2.8742803291927954 4.244696970603087 0.5367325403924951 'New Delhi']
 [1.4327205864731152 7.392391928503188 3.8712318740666514 'New Delhi']
 [4.650112288080132 1.6263131638056452 1.0505939891171812 'Pune']
 [6.696722228160592 0.2072401422399861 3.

In [7]:
print(y)

[61.35321792 33.9310784  45.54725745 38.78699119 64.52452158 21.82429649
 46.26930495 37.18388726 50.52093639 48.49925993 58.7084002  31.91702858
 50.08341193 27.04120314 36.54220619 49.00696583 63.98084178 45.48315445
 34.42227449 40.63200894 54.33482122 40.66102239 58.21185192 54.73691754
 48.49160355 70.26555015 69.38007675 29.99387159 32.94880374 49.98639859
 72.10713531 42.59193873 50.448532   50.39988232 72.04487885 52.73526493
 29.99859091 59.72338037 29.27380113 43.5563897  90.86517605 51.78486808
 75.13824539 72.91630605 70.81351778 49.5193101  56.08056466 56.36481885
 34.20714339 78.0132319 ]


## Encoding categorical data

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [3])],  remainder='passthrough')
print(ct)

X = np.array(ct.fit_transform(X))

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [3])])


In [9]:
print(X)






[[0.0 0.0 1.0 8.20475811907858 8.851691567052583 5.541915796453766]
 [0.0 1.0 0.0 7.384167208052879 0.29786024544546263 0.9133332440410924]
 [0.0 0.0 1.0 6.709420367634253 6.866250118762682 0.5602215602680827]
 [0.0 0.0 1.0 2.6185867213836103 2.4352722247822367 9.752400544516247]
 [0.0 1.0 0.0 9.492453803697988 1.8003594027005765 4.0009384506635115]
 [0.0 0.0 1.0 0.37576603722391577 1.3842668716348183 6.396029703962327]
 [0.0 1.0 0.0 5.489149445758447 6.44340864539905 4.03050107937026]
 [0.0 1.0 0.0 7.999986512159232 0.5191311274589538 2.0954801469345465]
 [1.0 0.0 0.0 8.921422662784611 3.4253335690767672 5.272097693438419]
 [0.0 1.0 0.0 3.7617682880904377 4.549142039893949 9.718867035590838]
 [1.0 0.0 0.0 2.908848728809585 9.590750163881113 9.531488100551908]
 [0.0 1.0 0.0 2.8742803291927954 4.244696970603087 0.5367325403924951]
 [0.0 1.0 0.0 1.4327205864731152 7.392391928503188 3.8712318740666514]
 [0.0 0.0 1.0 4.650112288080132 1.6263131638056452 1.0505939891171812]
 [1.0 0.0 0.0 6.

## Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train , y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)
y_test

array([32.94880374, 31.91702858, 58.7084002 , 51.78486808, 45.54725745,
       29.99387159, 29.27380113, 42.59193873, 58.21185192, 64.52452158])

## Training the Multiple Linear Regression model on the Training set

In [11]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

## Predicting the Test set results

In [13]:
y_pred = regressor.predict(X_test)

np.set_printoptions(precision=2)
print("\n\n\nPredicted  Actual")
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))




Predicted  Actual
[[42.12 32.95]
 [31.12 31.92]
 [61.78 58.71]
 [48.59 51.78]
 [51.92 45.55]
 [36.59 29.99]
 [23.09 29.27]
 [50.72 42.59]
 [46.97 58.21]
 [51.95 64.52]]


In [14]:

np.set_printoptions(precision=2)
print(np.concatenate((X_test ,y_pred.reshape(len(y_pred),1) ,y_test.reshape(len(y_test),1)) ,1))

[[0.0 1.0 0.0 0.16651108059044128 7.941285785428237 5.729273276820304
  42.11967966509791 32.94880373565855]
 [0.0 1.0 0.0 2.8742803291927954 4.244696970603087 0.5367325403924951
  31.12215175909779 31.91702857955716]
 [1.0 0.0 0.0 2.908848728809585 9.590750163881113 9.531488100551908
  61.78321343908835 58.70840020094917]
 [0.0 1.0 0.0 1.419924388529732 6.997457453031746 8.469294500875284
  48.59442878481551 51.784868083243275]
 [0.0 0.0 1.0 6.709420367634253 6.866250118762682 0.5602215602680827
  51.91580364849027 45.54725745271558]
 [1.0 0.0 0.0 2.0507282838256597 6.408146082709504 2.043361261181285
  36.585586132863 29.993871587759518]
 [1.0 0.0 0.0 0.27349521723176506 0.6056328633458852 6.369548622055856
  23.089135396509363 29.273801131167325]
 [0.0 1.0 0.0 4.0688069442828745 9.432992581549245 1.4405705782823377
  50.72343624065205 42.5919387287405]
 [1.0 0.0 0.0 4.039418201228346 7.993182606438472 1.8973131982510003
  46.97367990265039 58.21185192274485]
 [0.0 1.0 0.0 9.49245380

In [ ]:
len(y_pred)

In [ ]:
y_test

In [ ]:
y_pred

In [ ]:
help(np.random.rand)*10